### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by zhex900** [jimp-dev/jimp#1048]
"jimp": "^0.16.1",

error:

````
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:194:11)
    at new Buffer (buffer.js:281:3)
    at module.exports.Parser._parseChunkBegin (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:147371:19)
    at module.exports.SyncReader.process (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:148011:17)
    at module.exports (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:147238:10)
    at Object.exports.read [as image/png] (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:147604:10)
    at Jimp.parseBitmap (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:49151:53)
    at Jimp.parseBitmap (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:47837:32)
    at new Jimp (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:47790:13)
    at _construct (/Users/jake/Code/pam-kiosk-app/.webpack/main/index.js:46325:21) {

````

```
  const image = await Jimp.read(Electron.NativeImage.toPNG());
````

Does anyone know how to solve this?

**Comment by philiprenich** [comment]
It seems like this is coming from a dependency called "load-bmfont" according to this issue: https://github.com/oliver-moran/jimp/issues/662

The problem was fixed in that repo, but no release has been tagged yet for Jimp to pick up, though I did notice [this PR](https://github.com/oliver-moran/jimp/pull/1008) to just remove the dependency.

**Comment by philiprenich** [comment]
Whoops, apologise, it seems there was a new release, 1.4.1 https://github.com/Jam3/load-bmfont/pull/7 so it probably isn't that. Could be any number of dependencies then. Looks like `pngjs` had it as well. https://github.com/lukeapage/pngjs/pull/134 Seems like that was fixed in a later version than [Jimp depends on](https://github.com/oliver-moran/jimp/blob/master/packages/type-png/package.json) though which could be where this error stems from.

**Comment by hipstersmoothie** [comment]
This might be fixed. Would anyone here mind checking?

**Comment by DTCleanBrain** [comment]
@hipstersmoothie As of 2/13/23 running Jimp 0.22.4 inside of a Node 16 Lambda I am still getting the warning about Buffer Deprecation

**Comment by bdwellons** [comment]
Seeing the same issue. 0.22.10 inside Node 18.x Lambda. Buffer deprecation. Any work around?

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
